version: '3'

services:
 broker:
  build:
   #we need to specify context since docker-compose file is not at the same
   #level as the service folder.
   context: ./../broker
   dockerfile: ./../broker/broker.dockerfile

  #Always restart if the container dies.
  restart: always
  ports:
   #map port 8080 on my localhost to port 80 on the docker image.
   - "8080:80"
  deploy:
   # Define 1 replica for now.
   mode: replicated
   replicas: 1

 mongodb:
  image: 'mongo:4.2.16-bionic'
  ports:
   - "27017:27017"
  environment:
   MONGO_INITDB_DATABASE: logs
   MONGO_INITDB_ROOT_USERNAME: admin
   MONGO_INITDB_ROOT_PASSWORD: password
  volumes:
   - ./db-data/mongo/:/data/db